[project]
name = "feather-ai"
version = "0.1.0"
description = "The lightest Agentic AI Framework you'll ever see"
authors = [{ name = "Luca Bozzetti" }]
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"